/**
 * Token type constants for IndoriLang.
 * Centralized definition of all token types used throughout the compiler.
 */
export const TokenType = {
  // Basic token types
  IDENTIFIER: 'IDENTIFIER',
  NUMBER: 'NUMBER',
  STRING: 'STRING',
  OPERATOR: 'OPERATOR',
  PUNCTUATION: 'PUNCTUATION',
  EOF: 'EOF',

  // Keywords
  VAR_DECL: 'VAR_DECL',
  VAR_ASSIGN: 'VAR_ASSIGN',
  IF: 'IF',
  ELSE: 'ELSE',
  TRUE: 'TRUE',
  FALSE: 'FALSE',
  AND: 'AND',
  OR: 'OR',
  NOT: 'NOT',
  WHILE: 'WHILE',
  FOR: 'FOR',
  DO_WHILE: 'DO_WHILE',
  FUNCTION: 'FUNCTION',
  RETURN: 'RETURN',
  CONSOLE_LOG: 'CONSOLE_LOG',
  CONSOLE_WARN: 'CONSOLE_WARN',
  CONSOLE_ERROR: 'CONSOLE_ERROR',
  ALERT: 'ALERT',
  ARRAY_DECL: 'ARRAY_DECL',
  ARRAY_LENGTH: 'ARRAY_LENGTH',
  ARRAY_GET: 'ARRAY_GET',
  ARRAY_MAP: 'ARRAY_MAP',
  ARRAY_FILTER: 'ARRAY_FILTER',
  ARRAY_REDUCE: 'ARRAY_REDUCE',
  OBJECT_DECL: 'OBJECT_DECL',
  OBJECT_GET: 'OBJECT_GET',
  OBJECT_SET: 'OBJECT_SET',
  ASYNC: 'ASYNC',
  SLEEP: 'SLEEP',
  TRY: 'TRY',
  CATCH: 'CATCH',
  FINALLY: 'FINALLY',
  POHA_TIME: 'POHA_TIME',
  JALEBI_MODE: 'JALEBI_MODE',
  RAJWADA_MODE: 'RAJWADA_MODE',
  SARAFA_NIGHT: 'SARAFA_NIGHT',
} as const;

/**
 * Set of console statement token types.
 */
export const CONSOLE_STATEMENT_TYPES = new Set([
  TokenType.CONSOLE_LOG,
  TokenType.CONSOLE_WARN,
  TokenType.CONSOLE_ERROR,
]);

/**
 * Set of easter egg statement token types.
 */
export const EASTER_EGG_TYPES = new Set([
  TokenType.POHA_TIME,
  TokenType.JALEBI_MODE,
  TokenType.RAJWADA_MODE,
  TokenType.SARAFA_NIGHT,
]);

/**
 * Type for token type values.
 */
export type TokenTypeValue = typeof TokenType[keyof typeof TokenType];

/**
 * Operator constants for IndoriLang.
 * Centralized definition of all operators used throughout the compiler.
 */
export const Operator = {
  // Assignment
  ASSIGN: '=',
  
  // Equality
  EQUAL: '==',
  NOT_EQUAL: '!=',
  
  // Comparison
  LESS_THAN: '<',
  LESS_THAN_OR_EQUAL: '<=',
  GREATER_THAN: '>',
  GREATER_THAN_OR_EQUAL: '>=',
  
  // Arithmetic
  ADD: '+',
  SUBTRACT: '-',
  MULTIPLY: '*',
  DIVIDE: '/',
  
  // Increment/Decrement
  INCREMENT: '++',
  DECREMENT: '--',
} as const;

/**
 * Type for operator values.
 */
export type OperatorValue = typeof Operator[keyof typeof Operator];

/**
 * Set of operator characters that can form single or multi-character operators.
 */
export const OPERATOR_CHARS = new Set([
  Operator.ASSIGN,
  '!',
  Operator.LESS_THAN,
  Operator.GREATER_THAN,
  Operator.ADD,
  Operator.SUBTRACT,
  Operator.MULTIPLY,
  Operator.DIVIDE,
]);

/**
 * Error message prefix for IndoriLang compiler.
 */
const ERROR_PREFIX = '❌ Arre bhiya, kuch gadbad hai';

/**
 * Error message templates for IndoriLang compiler.
 * All error messages use this prefix for consistency.
 */
export const ErrorMessages = {
  PREFIX: ERROR_PREFIX,
  
  // Lexer errors
  UNEXPECTED_CHARACTER: (line: number, char: string) => 
    `${ERROR_PREFIX} line ${line}: Unexpected character '${char}'`,
  UNCLOSED_STRING: (line: number) => 
    `${ERROR_PREFIX} line ${line}: Unclosed string`,
  
  // Parser errors
  TOKENS_MUST_BE_ARRAY: `${ERROR_PREFIX}: Tokens must be an array`,
  INVALID_ASSIGNMENT_TARGET: (line: number) => 
    `${ERROR_PREFIX} line ${line}: Invalid assignment target`,
  UNEXPECTED_TOKEN: (line: number, token: string | number | null) => 
    `${ERROR_PREFIX} line ${line}: Unexpected token ${token}`,
  
  // Compiler errors
  SOURCE_CODE_MUST_BE_STRING: `${ERROR_PREFIX}: Source code must be a string`,
  INVALID_AST_NODE: `${ERROR_PREFIX}: Invalid AST node`,
  
  // Transpiler errors
  UNKNOWN_NODE_TYPE: (nodeType: string) => 
    `${ERROR_PREFIX}: Unknown node type ${nodeType}`,
  UNKNOWN_EXPRESSION_TYPE: (nodeType: string) => 
    `${ERROR_PREFIX}: Unknown expression type ${nodeType}`,
} as const;

/**
 * Expected token error messages for parser.
 * Used when a specific token is expected but not found.
 */
export const ExpectedMessages = {
  VARIABLE_NAME: 'Expected variable name',
  VAR_ASSIGN: 'Expected "laa_re" after variable name',
  FUNCTION_NAME: 'Expected function name',
  PARAMETER_NAME: 'Expected parameter name',
  CATCH_PARAMETER: 'Expected catch parameter',
  ARRAY_NAME: 'Expected array name',
  OBJECT_NAME: 'Expected object name',
  PROPERTY_KEY: 'Expected property key',
  PROPERTY_NAME: 'Expected property name',
  SEMICOLON: 'Expected semicolon',
  OPEN_PAREN: 'Expected "("',
  CLOSE_PAREN: 'Expected ")"',
  OPEN_BRACE: 'Expected "{"',
  CLOSE_BRACE: 'Expected "}"',
  OPEN_BRACKET: 'Expected "["',
  CLOSE_BRACKET: 'Expected "]"',
  ASSIGN_OPERATOR: 'Expected "="',
  COLON: 'Expected ":"',
} as const;

/**
 * Transpiler header and comment messages.
 */
export const TranspilerMessages = {
  HEADER_LINE_1: '// Generated by IndoriLang v1.0 Compiler',
  HEADER_LINE_2: '// Code to bhari hai re!',
} as const;
