// Generated by IndoriLang v1.0 Compiler
// Code to bhari hai re!


// IndoriLang Runtime Helpers
const bhiya_bol = console.log;
const bhiya_chitav = console.warn;
const bhiya_gadbad = console.error;
const bhiya_suna = (msg: string) => alert(msg);

// Easter eggs
const poha_time = (): string => {
  bhiya_bol("🍚 Poha time ho gaya re 😎");
  return "Poha time ho gaya re 😎";
};

const jalebi_mode = (): string => {
  const originalLog = bhiya_bol;
  bhiya_bol = (...args: any[]) => originalLog("🍬", ...args);
  return "Jalebi mode activated! 🍬";
};

const rajwada_mode = (): string => {
  const originalLog = bhiya_bol;
  bhiya_bol = (...args: any[]) => originalLog("👑", ...args);
  return "Rajwada mode activated! 👑";
};

const sarafa_night = (): string => {
  bhiya_suna("🌙 Sarafa chal reha hai 🌙");
  return "Sarafa chal reha hai 🌙";
};

// Sleep function
const ruk_re = (ms: number): Promise<void> => new Promise(resolve => setTimeout(resolve, ms));

// Array helpers
const ketlu_re = (arr: any[]): number => arr.length;
const nikaal_re = (arr: any[], index: number): any => arr[index];
const ghuma_map = (arr: any[], fn: (item: any, index: number) => any): any[] => arr.map(fn);
const chhaan_re = (arr: any[], fn: (item: any, index: number) => boolean): any[] => arr.filter(fn);
const ghuma_reduce = (arr: any[], fn: (acc: any, item: any) => any, init: any): any => arr.reduce(fn, init);

// Object helpers
const dikha_re = (obj: Record<string, any>, prop: string): any => obj[prop];
const badal_re = (obj: Record<string, any>, prop: string, value: any): void => { obj[prop] = value; };

// Error handler
globalThis.addEventListener('error', (e: ErrorEvent) => {
  bhiya_gadbad('❌ Arre bhiya, kuch gadbad hai line ' + (e.lineno || 'unknown') + ': ' + e.message);
});

bhiya_bol("Ram Ram bhiya log!");
poha_time();
